defaults: &defaults
    working_directory: ~/clark-entity
    docker:
        - image: node:11-alpine
version: 2
jobs:
    build:
    <<: *defaults
    steps:
        - checkout
        - run:
            name: Install Dependencies
            command: npm install